    5 CLS
   10 REM > P1A2-EXPONENTIATION-OPERATOR.BAS
   20 :
   25 REM https://github.com/learnagon/bbc-basic-by-example
   26 REM https://youtu.be/SvhfNCM13bo?si=OhxgCB1WMX_QP6rn
   28 :
   30 REM Source: BBC BASIC(Z80) for the Agon Light Manual
   40 REM https://oldpatientsea.github.io/agon-bbc-basic-manual/0.1/bbc2.html
   50 :
   60 REM ** Exponentiation ^ Operator **
   70 REM Binary operation of exponentiation between integers and reals.
   80 :
   85 PRINT
  100 : 
  105 PRINT
  110 PRINT "An example of the ^ operator is:"
  120 :
  125 result% = 2^2
  128 PRINT
  130 PRINT "2^2=";result%
  135 PRINT
  140 END
